version: '3'
services:
  umami:
    image: ghcr.io/mikecao/umami:postgresql-latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: H6ei6O1tdLNxIQLRs4Mw # change me
    depends_on:
      - umamudb
    restart: unless-stopped
  umamudb:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: porfoliosekiteh # change me
      POSTGRES_USER: seki # change me
      POSTGRES_PASSWORD: umami # change me
    volumes:
      - /home/seki/docker/umami/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - /home/seki/docker/umamu/umamudb:/var/lib/postgresql/data
    restart: unless-stopped