version: "2"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - ./Jackett:/config
      - /Torrents:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped