---
version: "2"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    mem_limit: 512M
    mem_reservation: 16M
    cpus: 0.25
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zagreb
    volumes:
      - /Jackett:/config
      - /Jackett/Downloads:/downloads
    ports:
      - 1000:9117
    restart: unless-stopped
    
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    mem_limit: 512M
    mem_reservation: 16M
    cpus: 0.25
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zagreb
    volumes:
      - /Radarr:/config
      - /Video/Filmovi:/movies
      - /Downloads:/downloads
    ports:
      - 2000:7878
    restart: unless-stopped
    
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    mem_limit: 512M
    mem_reservation: 16M
    cpus: 0.25
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zagreb
    volumes:
      - /Sonarr:/config
      - /Video/Serije:/tvs
      - /Downloads:/downloads
    ports:
      - 3000:8989
    restart: unless-stopped